GET http://localhost:8080/categoria/all

###

POST http://localhost:8080/categoria/save
Content-Type: application/json

{
    "id": null,
    "nome": "Cartão"
}

###

POST http://localhost:8080/categoria/delete
Content-Type: application/json

{
    "id": 1
}

###

POST http://localhost:8080/categoria/update
Content-Type: application/json

{
    "id": 1,
    "nome": "ODONTOLOGO"
}

