GET http://localhost:8080/conta/all

###

GET http://localhost:8080/conta/resumo

###

POST http://localhost:8080/conta/save
Content-Type: application/json

{
    "id": null,
    "categoria": {
        "id": 2
    },
    "tipo": true,
    "data": "2023-09-26",
    "descricao": "Dipirona",
    "valor": 6.20,
    "destinoOrigem": "Farmacia do Zé",
    "status": false
}

###

POST http://localhost:8080/conta/delete
Content-Type: application/json

{
    "id": 1
}

###

POST http://localhost:8080/conta/update
Content-Type: application/json

{
    "id": 1,
    "categoria": {
        "id": 2
    },
    "tipo": false,
    "data": "2023-09-26",
    "descricao": "algodao",
    "valor": 3.99,
    "destinoOrigem": "Farmacia",
    "status": false
}

